// 头部 tab 页面切换
export const CHANGE_HEADER_TAB = 'CHANGE_HEADER_TAB'
export const CHANGE_TYPES_TAB = 'CHANGE_TYPES_TAB'
export const CHANGE_MYLIST_TAB = 'CHANGE_MYLIST_TAB'
// 首页
export const SET_CATE_LIST = 'SET_CATE_LIST'
export const SET_RECOMMEND = 'SET_RECOMMEND'
export const SET_SUB_CATE_LIST = 'SET_SUB_CATE_LIST'
// 试卷
export const SET_PAPER_LIST = 'SET_PAPER_LIST'
export const SET_PAPER_DETAIL = 'SET_PAPER_DETAIL'